### ISSUE TITLE
Square image isn't showing for webinar

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#101]
We've uploaded the correct square image in WP:
![image](https://user-images.githubusercontent.com/81642726/116147520-afd0cf00-a694-11eb-845c-3e3ce6b1c3dd.png)

But it's showing the rectangular one in the grid:
![image](https://user-images.githubusercontent.com/81642726/116147474-9f205900-a694-11eb-9d65-880d243788d6.png)

https://librestream.com/webinars/

**Comment by paulstroot** [comment]
This is showing up properly on the development site. I believe there were some image optimization changes made recently. Can we see how it looks after merge the next pull request before moving forward with more troubleshooting?
Dev site: https://librestreamdevelop.gtsb.io/webinars/
CC: @tbeck and @samyue888

**Comment by samyue888** [comment]
Ok, please let me know once you merge. I see that correct square image is showing up on the live site now - strange.

**Comment by paulstroot** [comment]
I think it must have been a cached image. We can keep this open for a little but until our next merge just to make sure, but I think this issue is resolved.
