### ISSUE TITLE
Support form not sending to SF

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#102]
We've pasted the raw html code of the SF form here:
https://librestream.com/test/

as well as on our old site:
https://librestream.kinsta.cloud/test

We can see a test submission on SF from the old site but not the new site, hence verifying that there's something wrong with the new site that's blocking data going to SF.

Here's the html code:

<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">

<form action="https://webto.salesforce.com/servlet/servlet.WebToCase?encoding=UTF-8" method="POST">

<input type=hidden name="orgid" value="00DA0000000J3qY">
<input type=hidden name="retURL" value="https://librestream.com/form-confirmations/support-request-confirmation">

<label for="name">Contact Name</label><input id="name" maxlength="80" name="name" size="20" type="text" /><br>

<label for="email">Email</label><input id="email" maxlength="80" name="email" size="20" type="text" /><br>

<label for="phone">Phone</label><input id="phone" maxlength="40" name="phone" size="20" type="text" /><br>

<label for="subject">Subject</label><input id="subject" maxlength="80" name="subject" size="20" type="text" /><br>

<label for="description">Description</label><textarea name="description"></textarea><br>

<input type="hidden" id="external" name="external" value="1" /><br>

<input type="submit" name="submit">

</form>

**Comment by paulstroot** [comment]
I'm guessing that it will work okay if the same HTML that you put into the test page is put into the "Contact Support Librestream" page. I can put it in there for you if you like, but since the form was removed I don't recall if there was any accompanying text that showed up before the form, and also, I'm not sure if you want me to submit any test submissions of the form from my end, or if you want to do the testing. @samyue888, Do you want to just paste that form HTML in there and test it out immediately after you see the update? That might be the most efficient way to update and test.

**Comment by samyue888** [comment]
@paulstroot To clarify, this test page on the new site doesn't send to SF:
https://librestream.com/test/

We pasted the same html code into our old site and it sends to SF, thus confirming that something in the new site is blocking the send. We do not see your submission on SF yesterday evening.

**Comment by samyue888** [comment]
@paulstroot I'm free 10-11:30 and can verify on the SF side, if you want to jump on a call?

**Comment by paulstroot** [comment]
Hi sam. I just got back to my office. Do you want to jump on a call quick?

**Comment by samyue888** [comment]
Sorry, I'm in meetings til 10 PST

**Comment by paulstroot** [comment]
I made an update to the form on the "/test" page, and turned debugging on. When I submitted I got a message saying that "Your request has been queued", and I also got an email saying this:

```
A new case with id 5003k00001v7jvA has been successfully created.
To view the new case, go to
https://librestream.my.salesforce.com/5003k00001v7jvA
```

So it seems like this one worked. Can we get Liz or somebody to check the salesforce end of things?

**Comment by samyue888** [comment]
@paulstroot yup, I see this record on SF

**Comment by samyue888** [comment]
I'm available for the next hour. Let me know if you'd like to jump on a call. I'm having trouble creating recaptcha

**Comment by paulstroot** [comment]
Yes. I'm available for about another 30 minutes or so. I'll send out a
google meet link to you.

I think we'll work on making the form submit properly to SalesForce first,
and then I'll troubleshoot the recaptcha.

**Comment by paulstroot** [comment]
@samyue888 - Now that the form is back up on the live Contact Support page, could you do a test submission and see if it comes through to SF? (maybe you've already done this?) If so, then this can be closed.

**Comment by samyue888** [comment]
It sends properly to SF now, thanks
