### ISSUE TITLE
[Priority] Use case images aren't showing

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#104]
https://librestream.com/use-cases/

**Comment by samyue888** [comment]
And this page shows up w black squares:
https://librestream.com/industry-solutions/

**Comment by tbeck** [comment]
This fix is up and development site is building: https://librestreamdevelop.gatsbyjs.io/industry-solutions/

@samyue888 - the fix is part of the PR #103 which I believe that you have the ability to merge when ready.

**Comment by samyue888** [comment]
@tbeck This page is still showing up as empty: https://librestreamdevelop.gatsbyjs.io/use-cases/

**Comment by samyue888** [comment]
@tbeck @paulstroot Can we revert back to a previous working version until this has been fixed? Thanks

**Comment by tbeck** [comment]
@samyue888 - We have pushed a fix for that page as well now. It is also part of the PR #103

**Comment by samyue888** [comment]
@tbeck I'm looking at this page now in incognito, and the square images are still blank: https://librestreamdevelop.gatsbyjs.io/use-cases/
Is this the correct page?

**Comment by samyue888** [comment]
Working and pushed now. Thanks!
