### ISSUE TITLE
Question and Answer fields should not be mandatory

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#108]
For all support pages, the question and answer fields should not be mandatory:
![image](https://user-images.githubusercontent.com/81642726/116753258-a8beff00-a9bb-11eb-980f-21e74faed755.png)

Right now we have to add a '.' to bypass this.
eg. https://cms.librestream.com/wp-admin/post.php?post=12666&action=edit

**Comment by paulstroot** [comment]
@samyue888 - These are no longer mandatory fields. Please review. I'm not sure how to view this test page on the site. Let me know if there are some special display requirements for when a question or answer is left blank.
