### ISSUE TITLE
[Urgent] Form confirmation assets not showing

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#111]
All embedded PDF assets in form confirmations are not working, eg.
https://librestream.com/form-confirmations/verdantix-report/
https://librestream.com/form-confirmations/wbr-report/
https://librestream.com/form-confirmations/remote-expert-download-confirmation/
https://librestream.com/form-confirmations/lns-connected-worker-report/

**Comment by tbeck** [comment]
Closing - Pushed as part of #106
