### ISSUE TITLE
New items added to training page are not clickable

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#112]
I tried adding some items on a duplicate test page. Note that the pdf and video are not showing:
https://librestream.com/training-deployment-adoption-materials-2/

![image](https://user-images.githubusercontent.com/81642726/116939745-ba094500-ac21-11eb-9e54-7d783c5ab257.png)

**Comment by paulstroot** [comment]
@samyue888 - Please test this now. I think it may have been fixed with the last merge. I tested the items you added in the "TEST" section and all three are working for me.

**Comment by samyue888** [comment]
Works after the merge, thanks!
