### ISSUE TITLE
Internet Explorer main page display problems

### ISSUE THREAD

**Issue by lsdrew** [ocupop/librestream#113]
![image](https://user-images.githubusercontent.com/69823178/116950782-b7bbe080-ac4b-11eb-92f5-bca8e6efe597.png)

**Comment by tbeck** [comment]
@lsdrew - Can you provide browser and OS versions?
As well as any other relevant details to help troubleshoot this issue.

**Comment by paulstroot** [comment]
@lsdrew -I think I've got IE11 looking pretty good. The main issue happening was that background images were being placed as optimized WebP formats, which isn't supported in Internet Explorer. My fix was to make sure images that may be used as background images are always a JPG. This takes away a little bit of optimization, but I did not notice any big differences in lighthouse speed scores. There were also some javascript errors that came up in Internet Explorer that I fixed. I have this staged on it's own branch and can be viewed here: https://librestreamiefix.gatsbyjs.io/

Please review in IE11 and let me know if you come across any other concerning issues that must be fixed.

CC: @tbeck @samyue888

**Comment by samyue888** [comment]
@paulstroot When I run that link through the lighthouse test, the 'Serve images in next-gen formats' shows up again. Is there a way to only set jpg for IE, and next gen formats for other browsers?

![image](https://user-images.githubusercontent.com/81642726/118522728-3d7e6800-b6f1-11eb-9978-bbe5e00bebee.png)

**Comment by paulstroot** [comment]
No, we have not found a way to do this.

There may be a way to re-do the way that we build out background images so
that it uses the <picture> tag instead of a background image, but it may
take a few hours of development time, and it may not work at all with the
hero carousels. Tom and I discussed this and decided to bring that up later
as a lower priority since everything is working okay, and it does not seem
to be affecting page speed (only the page speed "score").

**Comment by lsdrew** [comment]
'Serve images in next-gen formats' may be a red herring. https://en.wikipedia.org/wiki/WebP#Criticism says jpeg processed by mozjpeg can be just as good as webp. https://en.wikipedia.org/wiki/Guetzli may also be as good as mozjpeg and webp for size and MOS rating. I do recommend that if they're being served as jpegs that we make sure that they're optimized.

**Comment by paulstroot** [comment]
The "gatsby-plugin-image" tool that we're using is known to do an excellent
job of optimizing images.

**Comment by samyue888** [comment]
It's working for us on IE now.
