### ISSUE TITLE
Arrow animation in navigation menu

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#116]
This arrow in the top menu should only show up when a user clicks on a section and there is a dropdown.
It should stay stationary and be centered to the section title (text)

![image](https://user-images.githubusercontent.com/81642726/117055818-77eb0c80-acd0-11eb-86f5-b2a52e674e34.png)

**Comment by paulstroot** [comment]
@samyue888 - I think we might need to think this through a little bit. It sounds like you're thinking that the arrow should indicate the active page, but only if the active page has a sub-menu, is that correct?

Would it make more sense if the active page indicator was different colored text? Then it could be visible whether the page has a sub-menu or not.

The arrow currently is a hover indicator. If you would like the arrow to be the active page indicator, then would we do something different to indicate hover?

**Comment by samyue888** [comment]
@paulstroot After some thought, let's just remove the arrow. As JS codes are affecting our site performance, it'll be best to reduce any non-essential animations like this. Thank you!

**Comment by paulstroot** [comment]
@samyue888 - I removed the arrow. This is ready for review on the dev site.
https://librestreamdevelop.gatsbyjs.io/

**Comment by samyue888** [comment]
The dev site looks good, thanks
