### ISSUE TITLE
Make email field not required

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#118]
Please make the 'Email' field not required for the below forms:
https://librestream.com/register-opportunity/
https://librestream.com/reseller-orders/

When updated, please wait for us to test submissions. Thanks!

**Comment by samyue888** [comment]
@paulstroot Please make 'email' and 'company' required as per Tim's request

**Comment by samyue888** [comment]
Other fields would not be required. Thanks

**Comment by paulstroot** [comment]
Got it. This has been updated. It's a WordPress change so the update has been made to both the dev site and the live site. Please review @samyue888 

LINK: https://librestream.com/register-opportunity/

**Comment by samyue888** [comment]
@paulstroot Thanks. Just spotted a small error - please make 'company' required, not 'country'.

**Comment by paulstroot** [comment]
Oops! Thanks you for catching that Sam. Updating now.

**Comment by samyue888** [comment]
It's working now, thanks
