### ISSUE TITLE
Reduce layout shift in hero

### ISSUE THREAD

**Issue by paulstroot** [ocupop/librestream#127]
After we had set the fonts to be non-blocking, a system fonts loads initially, which is then replaced by our web font once it loads. Since the system font and web font are different sizes they cause a **flash of unstyled text** in that moment between first page render and when the fonts loads. Website optimization tools often penalize a few points for sites that do this, plus it's not a very nice user experience to see the content jump around.

I've staged a fix on a new branch for review. The Hero text and H1 tags should first appear invisible until the font loads, and then fade in. This required some moving around of font files so it should be thoroughly tested before being merged into the development branch for a pull request.

Start with the home page, and surf through several other pages making sure the hero text loads properly. Try reloading pages, throttling network connection and any other ways to give variation to page loading. Please note if you see the layout break at any time. (and if so, can you recreate it? How?)

View it here: https://librestreamlayoutshift.gatsbyjs.io/

CC @samyue888, @lsdrew and @tbeck

**Comment by samyue888** [comment]
Inputing this into the Google performance test, it seems that this has a lower score that our current build:
librestreamlayoutshift.gatsbyjs.io, mobile: 29, desktop: 66
librestream.com, mobile: 31, desktop: 68

**Comment by paulstroot** [comment]
Have you done multiple tests? I often find google pagespeed insights varies
4-8 points each time I do a test.

I did not notice much performance increase, but I think it's a better user
experience.

**Comment by samyue888** [comment]
@paulstroot Thanks for the reminder. Yes, please push to a PR when ready.

**Comment by paulstroot** [comment]
This has been merged with the develop branch and pushed to live the next time there is a pull request.
