### ISSUE TITLE
Images not showing up on News Search Results

### ISSUE THREAD

**Issue by paulstroot** [ocupop/librestream#128]
Search results on the News page are not showing images.

**Comment by paulstroot** [comment]
@samyue888 - Fixed and ready for review. Type some text in the search bar and make sure the results look okay

https://librestreamdevelop.gatsbyjs.io/news/
https://librestreamdevelop.gatsbyjs.io/press-releases
https://librestreamdevelop.gatsbyjs.io/in-the-news
https://librestreamdevelop.gatsbyjs.io/events

**Comment by samyue888** [comment]
@paulstroot I noticed the search results aren't showing the square images:
![image](https://user-images.githubusercontent.com/81642726/119527906-9b383300-bd35-11eb-92f0-70e56b607df7.png)

Also, the search seems to bring up results from all categories. eg. If they search in blog, it should only bring up blog posts.

**Comment by paulstroot** [comment]
Update made and pushed to the develop branch. Please Review

https://librestreamdevelop.gatsbyjs.io/news/
https://librestreamdevelop.gatsbyjs.io/press-releases
https://librestreamdevelop.gatsbyjs.io/in-the-news
https://librestreamdevelop.gatsbyjs.io/events

**Comment by samyue888** [comment]
Looks great. Please push to PR when ready. Thanks
