### ISSUE TITLE
[Urgent] Bandwidth overuse warning

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#143]
@paulstroot @tbeck 

We've received this email from Kinsta yesterday. We risk having our site shut down and it seems we only have 1 business day to resolve this. Please advise on our next steps. Thanks
![image](https://user-images.githubusercontent.com/81642726/123135703-f4fc4d80-d406-11eb-9c0d-f9b3abcdd21f.png)

**Comment by tbeck** [comment]
Hi @samyue888 - This is the same issue that we have mentioned several times. Large files including video are being hosted and served from the WP instance. Our recommendation mirrors what Kinsta is saying. It is best to host these files on a streaming provider like YouTube or migrate large PDF's to cloud storage solution.  I believe that you are using Amazon in other instances.

I would respond back to Kinsta and state that you were unaware of the conflict with their terms of service and had no mal intent. You should ask if they will extend the 1 business day to allow you sufficient time to migrate them to YouTube. Although... this may be enough time for you to make those updates. 

I believe that we have logic in our templates to accommodate for YouTube hosted videos, but it would be great to coordinate a test prior to migrating all videos. Let me know how we can help.

**Comment by samyue888** [comment]
Can we move all files to AWS and do a redirect of cms.librestream.com/media/* to download.librestream.com/media/* ? How will this affect non-video files?

CC @lsdrew

**Comment by tbeck** [comment]
Our recommendation would be to use YouTube or Vimeo for video streaming     You can then use aws for downloads that don’t require a streaming server. ie… PDFs

**Comment by samyue888** [comment]
@tbeck As Youtube has a less ideal UX, we have moved all video files to our AWS. Are you able to add redirects to each of the videos here? 
https://cms.librestream.com/wp-admin/upload.php?mode=list&attachment-filter&m=0&media_category=0&media_sync_missing_files&filter_action=Filter&s=mp4&action=-1&paged=1&action2=-1&affected&_ajax_nonce=66416c9271&ps
They have the same filenames, so each redirect would be from cms.librestream.com/media/[filename] to download.librestream.com/media/[filename] 

Please let us know the timeline for this. Thank you!

**Comment by tbeck** [comment]
@samyue888 - We are not available to add these redirects. You will need to add them via the Kinsta admin. Here is an article describing the process for reference: https://kinsta.com/knowledgebase/redirect-rules/

**Comment by samyue888** [comment]
@tbeck Would redirects not be done via the json file in github?

**Comment by lsdrew** [comment]
Do you recommend any plugins for managing wp-content off site with or without gatsby?

**Comment by tbeck** [comment]
> @tbeck Would redirects not be done via the json file in github?

No... this is done in Kinsta following the directions outlined in the article I referenced.


@lsdrew 
> Do you recommend any plugins for managing wp-content off site with or without gatsby?

I'll let Paul weigh in on any specific plugin recommendations if any., but to be clear... we are recommending migrating only the media files (mpg, pdf, mov etc.) Not the entire wp-uploads (media) folder.

Video files need to be transcoded for web delivery and should be handled by a video hosting and streaming service. If you don't want to utilize You Tube or Vimeo, you can create your own VOD service using AWS. Needless to say, this is a very large lift. https://aws.amazon.com/cloudfront/streaming/ 

Ideally the management of these files is done outside of WP, and then source urls are added to the site using the WP content management tools. This way you avoid relying on WP to handle the upload/optimization and management of these large assets.

@lsdrew - I am happy to jump on a call to discuss if you would like?

**Comment by tbeck** [comment]
@lsdrew 
> Do you recommend any plugins for managing wp-content off site with or without gatsby?

I'll let Paul weigh in on any specific plugin recommendations if any., but to be clear... we are recommending migrating only the media files (mpg, pdf, mov etc.) Not the entire wp-uploads (media) folder.

Video files need to be transcoded for web delivery and should be handled by a video hosting and streaming service. If you don't want to utilize You Tube or Vimeo, you can create your own VOD service using AWS. Needless to say, this is a very large lift. https://aws.amazon.com/cloudfront/streaming/ 

Ideally the management of these files is done outside of WP, and then source urls are added to the site using the WP content management tools. This way you avoid relying on WP to handle the upload/optimization and management of these large assets.

@lsdrew - I am happy to jump on a call to discuss if you would like?

**Comment by tbeck** [comment]
@samyue888 - Following up here to check and see if you were able to resolve the issue and migrate video files?

**Comment by samyue888** [comment]
Yes, we have redirected to AWS now
