### ISSUE TITLE
[Urgent] PDFs broken due to / at the end

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#149]
In this page:
https://librestream.com/platform/remote-expert/
This button is not working.
![image](https://user-images.githubusercontent.com/81642726/126229394-1efb4894-e717-4564-99e9-b6006c2c4029.png)

I checked that the link in WP is correct. It seems to be auto-adding a slash at the end, causing it to break.

**Comment by paulstroot** [comment]
So it looks like the URL https://librestreamdevelop.gatsbyjs.io/media/LIB-platform-brochure-2021.pdf is redirecting to https://cms.librestream.com/media/LIB-platform-brochure-2021.pdf/, and it is that trailing slash that is causing the problem.

@tbeck - I think you were part of setting up the redirects functionality on the site. Is this something that you are able to quickly find and help me fix?

**Comment by paulstroot** [comment]
@sam - I discovered that this is definitely related to our redirects entered in Gatsby. I actually believe it's some sort of configuration setting on the hosting server. I've submitted a support ticket to Gatsby Cloud.

**Comment by samyue888** [comment]
@paulstroot Our team is spotting the same issue for other pdf links with / at the end. This is an urgent issue as several links are broken on the live site. Could we get a timeline for this?

cc @lsdrew

**Comment by paulstroot** [comment]
I have an open support issue with Gatsby Cloud and I'm waiting for their
response.

**Comment by samyue888** [comment]
@paulstroot I've contacted Gatsby support and they suggested this plugin: 
https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-trailing-slashes/

Perhaps this would help?

**Comment by samyue888** [comment]
@paulstroot I've changed the https to http as a temporary fix. Note that this still requires a prompt fix as external links would still not work.

**Comment by paulstroot** [comment]
I took a look at that link and the first couple of lines tell me that this
plug-in isn't going to solve our issue.

"This plugin is intended to remove trailing slashes from paths generated by
Gatsby itself. This however does not prevent the resolution of pages that
have trailing slashes, due to the way browsers are built to interpret URLs
as paths. This means that a user will need to take the extra step of
ensuring that all router links direct towards paths that do not end in a
slash."

Our pages are correctly interpreting the links placed on the page without
the trailing slash. The problem has something to do with how the site or
the server is choosing to execute the redirects.

I haven't heard from Gatsby support yet so I'll submit another ticket. Do
we have a direct phone line to their support team? If I can track that down
I can try to call tomorrow.

**Comment by samyue888** [comment]
@paulstroot I couldn't find a phone, but you can email them via this contact us button and they reply within a day:
![image](https://user-images.githubusercontent.com/81642726/126684072-f91652b8-702f-4f23-b1cb-9747937fa286.png)

![image](https://user-images.githubusercontent.com/81642726/126684018-6268563d-9ace-4d08-9a94-f972395f986c.png)

**Comment by paulstroot** [comment]
Yes. That is how I contacted them. They replied with the same plug-in
suggested that they told you, which will not work, so I am continuing the
conversation with some more details. I"ll let you know when I get a reply.

**Comment by samyue888** [comment]
@paulstroot Another idea that came up. The pdfs on the training page are all static links which work: https://librestream.com/training-deployment-adoption-materials/

Could we somehow change all pdf links to static to resolve this?

**Comment by paulstroot** [comment]
Here is the latest from Gatsby Cloud. Hopefully they will fix it soon with
no changes needed on our end.


Hi Paul,

Thanks for sharing the redirect configuration. I traced this issue to how
we handle redirects on the Gatsby Hosting server. We automatically add a
trailing slash for any redirects. This is a bug and I'll work with our
Cloud engineers to get this corrected. I'll follow up as soon as I have an
update.

**Comment by samyue888** [comment]
@paulstroot Thanks for the update. In the meantime, is there a temporary solution we can implement? These broken pdf links have occurred for several days now, which is taking a toll on our business.

**Comment by paulstroot** [comment]
The only temporary fix I can think of is actually a permanent fix, which is
to move all of your PDF files to a CDN, which we have been suggesting for a
while now.

**Comment by paulstroot** [comment]
@samyue888 - This message from Gatsby Cloud this morning 
_"We have a fix forthcoming that is currently in review. I'll let you know when it is ready."_

**Comment by paulstroot** [comment]
@samyue888 - Checked in with them a gain today. This is their response:
_We are close but I'm still conferring with our Cloud engineers to see why we haven't closed the loop on this yet. I apologize for any inconvenience. Someone from from our support team will check in with you tomorrow with an update._

**Comment by paulstroot** [comment]
@samyue888 - Another update from gatsby cloud today:
_...Just wanted to chime in here and let you know we plan to have the fix out early next week._

**Comment by paulstroot** [comment]
@samyue888 - I just got word that this issue has been fixed!
