### ISSUE TITLE
Add recaptcha solution for SF embedded form

### ISSUE THREAD

**Issue by tbeck** [ocupop/librestream#60]
**Describe the solution you'd like**
add recaptcha to support form https://librestream.gtsb.io/contact-us-support/

**Comment by paulstroot** [comment]
@tbeck This is working pretty consistently for me now.  The script tag need a "async defer" on it. Please test on your end in an incognito window. This was a chage in WordPress so the update was made on both the live site and the develop site.

https://librestream.com/contact-us-support/

**Comment by samyue888** [comment]
It works now, but could we add some whitespace between the recaptcha and submit button: 
![image](https://user-images.githubusercontent.com/81642726/115604585-664c4280-a296-11eb-9531-6338859408ac.png)

**Comment by samyue888** [comment]
And also reduce the whitespace at the  top of the form:
![image](https://user-images.githubusercontent.com/81642726/115604659-78c67c00-a296-11eb-894a-875c756782de.png)

**Comment by paulstroot** [comment]
A little extra space has been added. @samyue888 please review. This was done in wordpress so the update should be displayed on both the staging site and the live site.

**Comment by samyue888** [comment]
Thanks @paulstroot , Could you also remove the whitespace at the top of the form? Thanks

**Comment by paulstroot** [comment]
Sure @samyue888 . I just tightened up that space a bit.
https://librestream.com/contact-us-support/

**Comment by samyue888** [comment]
@paulstroot Thanks. I've found a strange bug: If I go to the support form page from another page, eg. from https://librestream.com/contact-us , the recaptcha doesn't show. I tried in incognito too.

**Comment by paulstroot** [comment]
Thanks. I'll put it on my to-do list to check out. I'm sure it has
something to do with how Gatsby does initial load and subsequent page loads.

**Comment by paulstroot** [comment]
@samyue888 - I got the recaptcha to load even if it's a subsequent page on the development site.
https://librestreamdevelop.gatsbyjs.io/contact-us-support/

I'm getting "Invalid domain for site key" on the recpatcha though. I can not remember if the domain "https://librestreamdevelop.gatsbyjs.io/" is on the list of allowed domains for this recaptcha. Are you able to check on this and add it if it's not there already. Hopefully that will fix it and it will be ready to push to the live site.

**Comment by samyue888** [comment]
@paulstroot I'll send out an email to the team in charge of recaptcha and CC you

**Comment by paulstroot** [comment]
I saw Lee's email about adding the new domain to the captcha, and I'm still getting a "Invalid domain for site key" error. Do we maybe want to set up a new captcha so we're absolutely sure we are using the correct api key with the account that has the correct allowed domains?

**Comment by samyue888** [comment]
I see that it is working now.
https://librestreamdevelop.gatsbyjs.io/contact-us-support/

Please let me know the steps to setup a new recaptcha, if necessary

**Comment by paulstroot** [comment]
@samyue888 - try this
https://morweb.org/support-post/set-up-google-recaptcha

We want to set up Recaptcha V2 (checkbox style)

And we want to make sure these domain names are whitelisted:
*.librestream.com
librestreamdevelop.gatsbyjs.io
localhost:8000

Once set up there should be a couple of API keys that I will need.

**Comment by samyue888** [comment]
@paulstroot I managed to create a recaptcha v2. Hope this helps
![image](https://user-images.githubusercontent.com/81642726/116459310-7d50de80-a81a-11eb-8d4e-c3f16b3cef5d.png)

6Lcdu70aAAAAAPXJw-zXwUNk7ulMJtwGifOBRTsS
6Lcdu70aAAAAAFgKcrj5gMkcf1UrTvqqyM-I9vPP

https://www.google.com/u/4/recaptcha/admin/site/448641821

**Comment by paulstroot** [comment]
Thanks Sam. I'll give this one a shot. Did you add localhost, *.
librestream.com and https://librestream.gatsbyjs.io/ to the list of domains
for this recaptcha?

**Comment by samyue888** [comment]
Sure: 
![image](https://user-images.githubusercontent.com/81642726/116460448-ee44c600-a81b-11eb-8f89-ded23eb6a21d.png)

**Comment by samyue888** [comment]
Oh the * one doesn't work:
![image](https://user-images.githubusercontent.com/81642726/116460539-0288c300-a81c-11eb-8b83-40e118679a0b.png)

**Comment by paulstroot** [comment]
Hi @samyue888 . This new recaptcha you set up for us is working great for us. Could you please add this domain name to the list of allowed domains?
librestreamdevelop.gatsbyjs.io

**Comment by samyue888** [comment]
@paulstroot Added. Please send me a develop link to the form to test in SF when ready. Thanks

**Comment by samyue888** [comment]
@paulstroot I noticed you were editing the /contact-us-support/ page. Let's do all testing on /test/ and we can paste the form code over once confirmed to work. Thanks

**Comment by paulstroot** [comment]
Certainly

**Comment by paulstroot** [comment]
@samyue888 and @tbeck - I believe I have this working properly now. We are now using recaptcha version V3 instead of V2. That means that there is not a checkbox, but instead an invisible field that detects whether or not the user is a human. right now, you should see a badge in the lower right corner of the page. This confirms that the recaptcha is loading properly. Once we can review and confirm that with everybody, I can hide that badge with CSS.

Here is the test link: https://librestreamdevelop.gatsbyjs.io/test-recaptcha-v3/

Testing to see if this captcha is actually preventing spam is a little bit tricky. One form thread I read said "Google will take 3-4 days to collect the data and then its will display the graph in “Manage your reCAPTCHA API keys”.

Please test and confirm that you are seeing the badge on this test page. If it is working, I will hide the badge and we can do a pull request. After going live we can then put the form back on the contact support page.

Please also test submitting the form, which is issue #102. I did a test on my end and it redirected to the confirmation page successfully. Can we have somebody check that this came through in SalesForce?

**Comment by samyue888** [comment]
@paulstroot I've verified that it can push to SF

**Comment by samyue888** [comment]
@paulstroot Quick question. If we hide the recaptcha logo, how do we tell that it's actually there and working?

**Comment by paulstroot** [comment]
We can tell it's there by looking at the source code on the site.

Testing to see if this captcha is actually preventing spam is a little bit tricky. One form thread I read said "Google will take 3-4 days to collect the data and then its will display the graph in “Manage your reCAPTCHA API keys”.

**Comment by samyue888** [comment]
@paulstroot After submitting the form here: https://librestream-develop.gtsb.io/test/

It takes me to the wrong page: https://librestream.com/onsight-support/ and my submission was not sent to SF

**Comment by paulstroot** [comment]
Use this link to test from please:
https://librestreamdevelop.gatsbyjs.io/test-recaptcha-v3/

**Comment by samyue888** [comment]
Thanks for clarifying. The above form sends correctly to SF.

**Comment by samyue888** [comment]
Working after merge. Thanks
