### ISSUE TITLE
all external links should open in new tab

### ISSUE THREAD

**Issue by tbeck** [ocupop/librestream#67]

**Comment by tbeck** [comment]
@samyue888 - Can you provide an example where this is not working as expected? I know that we have fixed instances where we are pulling from a link marked as "external" in the cms. But there may be additional instance that we are unaware of or that are not covered by the current logic.

Thanks

**Comment by samyue888** [comment]
Here are some examples:
https://librestream.gatsbyjs.io/blog/4-disruptors-workers-environment/
https://librestream.gatsbyjs.io/blog/monetize-services-iot/
https://librestream.gatsbyjs.io/blog/achieve-business-model-innovation/

**Comment by samyue888** [comment]
If you haven't already, please also add Drew to these comment threads. Thanks

**Comment by tbeck** [comment]
> If you haven't already, please also add Drew to these comment threads. Thanks

@lsdrew - Adding you as per Sam's request. 
Sam... you can use use the "@" symbol to make sure that someone has visibility if needed

**Comment by tbeck** [comment]
@samyue888 - Thanks for providing examples. These are editable through the cms. Here is a screen shot of the specific link editor modal that you should indicate if a link should "open link in a new tab" or not.

<img width="610" alt="Screen Shot 2021-04-16 at 11 53 40 AM" src="https://user-images.githubusercontent.com/242469/115070995-85b82980-9eaa-11eb-851a-8d88ea616b36.png">
