### ISSUE TITLE
Undocumented gatsby warnings

### ISSUE THREAD

**Issue by lsdrew** [ocupop/librestream#79]
There are gatsby warnings and it's not clear if these are expected or if there will be any consequence.

1. Go to https://www.gatsbyjs.com/dashboard/dc5c64f1-456d-477f-baa4-7d974a20c9a4/sites/994efcf0-b7bb-4e52-a215-cb1fbb0d7300/builds/32d223f4-069a-4986-b761-e4227ef4bb7a/details#rawLogs
2. Click on 'Warnings'
4. See warnings

Expected behavior:
No warnings, or somewhere that expected warnings are described like readme.md for this project.

**Comment by tbeck** [comment]
@lsdrew - It looks like there are two different types of warnings being generated. 

1. `The GraphQL query in the non-page component /usr/src/app/www/src/templates/standalone/Campaign-Video.js will not be run.`

It looks like templates that were created based on the design are no longer being referenced from any pages. We can either leave as is, or remove these templates in both the CMS as well as the Gatsby project. Let me know what you would prefer. @samyue888 

2. `Css Minimizer Plugin: cssnano: /usr/src/app/www/styles.c3155a5177547d7fe285.css:139:5: Error in parsing SVG: Non-whitespace before first tag.`

This warning is generated when the css minimizer parses an SVG file created in tools like Adobe Illustrator. It is safe to ignore, or this can be adjusted in the SVG markup prior to design/asset handoff.
