### ISSUE TITLE
Add auto height adjustment for iframe forms

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#88]
We currently have this problem: https://jacobfilipp.com/iframe-height-autoresize-crossdomain/

I have pasted the js code on the Pardot side

**Comment by paulstroot** [comment]
@samyue888 , could you please send me a URL of a page with a Pardot iFrame so I can know where to test this one out?

**Comment by samyue888** [comment]
Sure, here are a few:
https://librestream.com/free-demo/
plus any of these:
https://librestream.com/resources

**Comment by paulstroot** [comment]
Than you @samyue888 . I've applied the JavaScript fix to the development site. Please test and review. Here are three test pages.

https://librestreamdevelop.gatsbyjs.io/resources/remote-expert-guide/
https://librestreamdevelop.gatsbyjs.io/free-demo/
https://librestreamdevelop.gatsbyjs.io/resources/lns-connected-worker-report/

**Comment by samyue888** [comment]
Perfect, thank you!
