### ISSUE TITLE
Add ability to edit media url in WP

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#92]
Currently, all new media uploads go to cms.librestream.com/media/*

We'd like to have the option to edit this to become eg. cms.librestream.com/media/pdf/*
Since some of the old links have /media/pdf

We are unable to edit the file URL here:
![image](https://user-images.githubusercontent.com/81642726/115464184-8a018100-a1e1-11eb-9ff1-7abbed2d3d91.png)

**Comment by paulstroot** [comment]
@samyue888, since there are currently some PDF files on the server in the "/media/pdf" directory, do you know how those were added previously? Was it done through the Wordpress admin, or were they uploaded manually to the server through FTP or another method? 
(CC @tbeck )

**Comment by paulstroot** [comment]
@samyue888 - I added the plug-in "Media Library Folders for WordPress" to the CMS. Looks like you were using this previously so hopefully it's familiar. You can now go to the admin section and click "Media Library Folders" in the navigation to bring up a page that will allow you to move files in the media-folder into sub-folders.

One thing to note, if you move a media file into a sub-folder, that might not mean that all references to that file will be automatically updated. If the URL of the file is pasted into an advanced custom field, or directly in the content editor on a page, you will need to update that path manually. For example, on the "IT & Security" page, the PDF "/media/Librestream-GDPR-FAQs.pdf" is linked to in the content editor. If you move this file into the "PDFs" folder, you will need to update this link also.

If the media files is linked as a featured image, or linked to an "image" type advanced custom field, it should update automatically.

One more thing. The documentation for this plug-in says that the PRO version works well with the "Enhanced Media Library" plug-in, which we are also using. allows for the folders set with one plug-in to sync with the other. This is $39 if you're interested in upgrading

Please test a couple media file updates and let me know if it's working properly!

CC: @tbeck

**Comment by samyue888** [comment]
Got it, thanks Paul!
