### ISSUE TITLE
Page titles missing

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#94]
All blogs, news, other resource pages, etc seem to be missing page titles (ie. only the URL shows):
![image](https://user-images.githubusercontent.com/81642726/115467594-9dfbb180-a1e6-11eb-8bee-6de5379d605b.png)

https://librestream.com/blog/how-raytheon-missiles-and-defense-uses-onsight-to-maximize-business-outcomes/
https://librestream.com/resources/lns-connected-worker-report/
https://librestream.com/press-releases/grocery-giant-tesco-receives-top-supply-chain-award-for-its-implementation-of-librestreams-onsight-augmented-reality-technology/

**Comment by tbeck** [comment]
@samyue888 - The fix has been pushed and is part of #95

**Comment by samyue888** [comment]
Thanks @tbeck Just one more thing to add. For all 404 pages, could you please add a 'Page Not Found' or '404' in the title? I'll need a consistent title for these to track 404s in GA.

**Comment by paulstroot** [comment]
I set the title to "**Librestream | page not found**".

@samyue888 please review.
https://librestreamdevelop.gatsbyjs.io/this-is-a-404-page

**Comment by samyue888** [comment]
@paulstroot That's perfect, thanks!
