### ISSUE TITLE
Please highlight the subheading for each feature subpage

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#96]
Please see the design comp:

![image](https://user-images.githubusercontent.com/81642726/115747172-d536a380-a349-11eb-8db4-c1a90beb482b.png)

**Comment by paulstroot** [comment]
Updated on development. @samyue888 please review.
https://librestreamdevelop.gatsbyjs.io/platform/digital-work-instructions/

It occurred to me after I pushed this that some pages (the about page for example), have anchor links, and so it will never have an "active" link, and all of the sub-navigation links now are blue instead of white. is this the desired behavior?
https://librestreamdevelop.gatsbyjs.io/about/

**Comment by samyue888** [comment]
@paulstroot The blue text in the about page will be suffice for now - thanks! Could we also add an arrow pointing to the correct platform feature like so:
![image](https://user-images.githubusercontent.com/81642726/115901661-565b6c80-a416-11eb-87ba-f4e077a64195.png)

**Comment by paulstroot** [comment]
Yes. I will work on that. Should I have the arrow only display on tablet and mobile, where the sub-navigation could potentially wrap to two lines?
![image](https://user-images.githubusercontent.com/52838369/115911347-95e48180-a433-11eb-9df4-7a8fad6a23b5.png)

**Comment by paulstroot** [comment]
@samyue888 - Bumping this up on your list for approval. This can go live with our next pull request if it's looking okay on your end.

**Comment by samyue888** [comment]
It looks good to push. Thank you!

**Comment by samyue888** [comment]
@paulstroot Oh! One thing I noticed in the dev site is that the banner image is not locked bottom left:
![image](https://user-images.githubusercontent.com/81642726/116288130-0c3ff700-a746-11eb-9ff1-44ee1cc9a581.png)

It should show an image like this:
![image](https://user-images.githubusercontent.com/81642726/116288172-1661f580-a746-11eb-84e4-cf6daf9c9cff.png)

**Comment by samyue888** [comment]
@paulstroot Yes, please only have the arrow for desktop. How it is on the dev site now is fine.

**Comment by paulstroot** [comment]
I think this can be checked off of our issues list then.

**Comment by samyue888** [comment]
Ok. Before I close, just want to confirm that the image will be locked bottom left upon merge? Thanks

**Comment by paulstroot** [comment]
Yes. Good catch. This needed some attention after our image optimizations. I'm uploading an update right now. @samyue888 - Please review and close if it's looking okay.
