### ISSUE TITLE
Add popup for home page CTA

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#97]
For this WATCH IN ACTION button, could we get a lightbox with the youtube video instead of taking them to a separate page?
![image](https://user-images.githubusercontent.com/81642726/115904046-2e213d00-a419-11eb-882d-4e85badb4039.png)

**Comment by paulstroot** [comment]
Hi @samyue888 . I'm working on this today and tomorrow. For this lightbox window, would you like only the video to display, or would you like the title and description to display above it like it does on the "Watch Onsight in Action" page?

**Comment by samyue888** [comment]
Just the video is fine for now, but could you add an option in WP for us to add text if needed? Thanks

**Comment by paulstroot** [comment]
@samyue888 - This is ready for review. The content of the popup can be edited in the WordPress CMS admin section for the home page.
https://librestreamdevelop.gtsb.io/

Admin page to edit: https://cms.librestream.com/wp-admin/post.php?post=14&action=edit

**Comment by samyue888** [comment]
It looks great, thanks!
