### ISSUE TITLE
For support page menu, add ability to link to page directly

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#99]
For this page 
https://librestream.com/onsight-support/

Specifically for this section in the left menu:
![image](https://user-images.githubusercontent.com/81642726/116119693-8d7a8980-a673-11eb-8c11-faa80488dbfe.png)

Could we link Release Bulletins and Notes directly to pages, instead of as anchors?
Please link to these respectively:
https://librestream.com/release-bulletin/
https://librestream.com/release-notes/

**Comment by paulstroot** [comment]
@samyue888 - This is ready for review on the dev site.
https://librestreamdevelop.gatsbyjs.io/onsight-support/

In the admin, you can now designate whether you want the link to go to an anchor, or to another page:
![image](https://user-images.githubusercontent.com/52838369/116300481-8f704580-a764-11eb-80e8-c8be81b13e1b.png)

**Comment by samyue888** [comment]
That's perfect, thanks!
